nameOverride: ""
fullnameOverride: ""

image: ghcr.io/itrooz/sccache:archlinux
imagePullPolicy: Always

# Scheduler service
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

scheduler:
  podAnnotations: {}
  podLabels: {}
  livenessProbe:
    httpGet:
      path: /health
      port: scheduler
  readinessProbe:
    httpGet:
      path: /ready
      port: scheduler
  config: {}
    # Additional scheduler configuration can be added here
    # Example:
    # max_idle_time = "3600s"
    # heartbeat_timeout = "30s"

worker:
  podAnnotations: {}
  podLabels: {}
  nodeSelector:
    sccache_worker: "true"
  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /ready
      port: http
  config: {}
    # Additional worker configuration can be added here
    # Example:
    # max_connections = 100
    # idle_timeout = "600s"
    # cache_size_limit = "10G"

app:
  token: "" # set in values.local.yaml
  secretKey: "" # set in values.local.yaml
