services:
  scheduler:
    image: ghcr.io/itrooz/sccache:custom
    command: ["scheduler", "--config", "/etc/sccache/scheduler.conf"]
    user: nobody
    environment:
      SCCACHE_NO_DAEMON: "1"
      SCCACHE_LOG: "sccache=info"
    volumes:
      - ./scheduler.conf:/etc/sccache/scheduler.conf:ro
    ports:
      - "7634:7634"
    networks:
      sccache-net:
        ipv4_address: 172.29.0.3

  worker:
    image: ghcr.io/itrooz/sccache:custom
    command: ["server", "--config", "/etc/sccache/worker.conf"]
    environment:
      SCCACHE_LOG: "sccache=info"
    privileged: true
    depends_on:
      - scheduler
    volumes:
      - ./worker.conf:/etc/sccache/worker.conf:ro
      - sccache-cache:/cache
    ports:
      - "10501:10501"
    networks:
      sccache-net:
        ipv4_address: 172.29.0.2

volumes:
  sccache-cache:

networks:
  sccache-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
