services:
  scheduler:
    image: ghcr.io/itrooz/sccache:custom
    command: ["scheduler", "--config", "/etc/sccache/scheduler.conf"]
    user: nobody
    environment:
      SCCACHE_NO_DAEMON: "1"
      SCCACHE_LOG: "sccache=info"
    volumes:
      - ./scheduler.conf:/etc/sccache/scheduler.conf:ro
    ports:
      - "7634:7634"
    networks:
      sccache-net:
        ipv4_address: 172.29.0.3

# Note: this build jobs isolation makes the build server somewhat privileged (note comments below)
# The below permissions are the reduced subset of --privileged that are needed to run it
# It should be run under a user namespace when possible
  worker:
    image: ghcr.io/itrooz/sccache:custom
    command: ["server", "--config", "/etc/sccache/worker.conf"]
    environment:
      SCCACHE_LOG: "sccache=info"
    cap_add:
      - SYS_ADMIN # Needed for the first `unshare -m` call
    security_opt: # Needed to create namespaces for jobs (handled by bwrap)
      - seccomp=unconfined
      - systempaths=unconfined
    depends_on:
      - scheduler
    volumes:
      - ./worker.conf:/etc/sccache/worker.conf:ro
      - sccache-cache:/cache
    ports:
      - "10501:10501"
    networks:
      sccache-net:
        ipv4_address: 172.29.0.2

volumes:
  sccache-cache:

networks:
  sccache-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
