# Bind address. Not needed to be public
public_addr = "0.0.0.0:7634"

[client_auth]
type = "token"
token = "CHANGEME_pc_to_scheduler_token"

[server_auth]
type = "token"
token = "CHANGEME_builder_to_scheduler_token"
