cache_dir = "/cache"
# PUBLIC address of the worker, used to connect to it. NOT 0.0.0.0
public_addr = "172.29.0.2:10501"
bind_address = "0.0.0.0:10501"
scheduler_url = "http://scheduler:7634"

[builder]
type = "overlay"
# The directory under which a sandboxed filesystem will be created for builds.
build_dir = "/volume/build"
# The path to the bubblewrap version 0.3.0+ `bwrap` binary.
bwrap_path = "/usr/bin/bwrap"

[scheduler_auth]
type = "token"
token = "CHANGEME_builder_to_scheduler_token"
