apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sccache.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/component: scheduler
    {{- include "sccache.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
      {{- include "sccache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/scheduler-configmap.yaml") . | sha256sum }}
        {{- with .Values.scheduler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/component: scheduler
        {{- include "sccache.labels" . | nindent 8 }}
        {{- with .Values.scheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: scheduler
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["sccache-dist"]
          args: ["scheduler", "--config", "/etc/sccache/scheduler.conf"]
          volumeMounts:
            - name: config
              mountPath: /etc/sccache
              readOnly: true
          env:
            - name: SCCACHE_NO_DAEMON
              value: "1"
            - name: SCCACHE_LOG
              value: "sccache={{ .Values.app.loglevel }}"
          ports:
            - containerPort: 7634
              name: scheduler
          {{- with .Values.scheduler.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.scheduler.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "sccache.fullname" . }}-scheduler-config