apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sccache.fullname" . }}-scheduler-config
  labels:
    app.kubernetes.io/component: scheduler
    {{- include "sccache.labels" . | nindent 4 }}
data:
  scheduler.conf: |
    # Public address that clients will use to connect to the scheduler
    public_addr = "0.0.0.0:7634"

    [client_auth]
    type = "token"
    token = "{{ .Values.app.token }}"

    [server_auth]
    type = "jwt_hs256"
    secret_key = "{{ .Values.app.secretKey }}"

    {{- with .Values.scheduler.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
