apiVersion: v1
kind: Service
metadata:
  name: {{ include "sccache.fullname" . }}-scheduler
  labels:
    {{- include "sccache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: scheduler
      protocol: TCP
      name: scheduler
    - port: 7634 # for internal access from workers
      targetPort: scheduler
      protocol: TCP
      name: scheduler-internal
  selector:
    app.kubernetes.io/component: scheduler
    {{- include "sccache.selectorLabels" . | nindent 4 }}
