apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sccache.fullname" . }}-worker-proxy-config
  labels:
    app.kubernetes.io/component: worker
    {{- include "sccache.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        # To resolve internal DNS names given to us by the worker
        resolver kube-dns.kube-system.svc.cluster.local valid=30s;
        
        server {
            listen 8080;
            
            # Handle CONNECT requests for HTTPS
            location / {
                proxy_pass $scheme://$http_host$request_uri;
                proxy_set_header MyHeader "sccache-worker";
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP ${NODE_IP};
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /healthz {
                access_log off;
                return 200 'ok';
                add_header Content-Type text/plain;
            }
        }
    }
