apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sccache.fullname" . }}-worker-config
  labels:
    app.kubernetes.io/component: worker
    {{- include "sccache.labels" . | nindent 4 }}
data:
  worker.conf: |
    cache_dir = "/cache"
    bind_address = "0.0.0.0:10501"
    public_addr = "${NODE_IP}:30501" # service will do 30501->10501
    scheduler_url = "{{ printf "http://%s-scheduler.%s.svc.cluster.local:7634" (include "sccache.fullname" .) .Release.Namespace }}"

    [builder]
    type = "overlay"
    # The directory under which a sandboxed filesystem will be created for builds.
    build_dir = "/tmp/build"
    # The path to the bubblewrap version 0.3.0+ `bwrap` binary.
    bwrap_path = "/usr/bin/bwrap"

    [scheduler_auth]
    type = "token"
    token = "{{ .Values.app.scheduler_token }}"
    
    {{- with .Values.worker.extra_config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
