apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sccache.fullname" . }}-worker
  labels:
    app.kubernetes.io/component: worker
    {{- include "sccache.labels" . | nindent 4 }}
spec:
  # To allow updating more at the same time
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      {{- include "sccache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/worker-configmap.yaml") . | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/component: worker
        {{- include "sccache.labels" . | nindent 8 }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      nodeSelector:
        {{- toYaml .Values.worker.nodeSelector | nindent 8 }}
      containers:
        - name: worker
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["sccache-dist"]
          args: ["server", "--config", "/etc/sccache/worker.conf"]
          volumeMounts:
            - name: config
              mountPath: /etc/sccache
              readOnly: true
            - name: cache
              mountPath: /cache
          ports:
            - containerPort: 3000
              name: worker
          {{- with .Values.worker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "sccache.fullname" . }}-worker-config
        - name: cache
          emptyDir:
            sizeLimit: 10Gi
